<?php

return [
    '/' => 'index',
    '/update' => 'index',
    '/delete' => 'index',
    '/insert' => 'index',
    '/about' => 'about',
    '/about/' => 'about',
    '/about/update' => 'about',
    '/about/delete' => 'about',
    '/about/insert' => 'about',
    '/gallery' => 'gallery',
    '/gallery/' => 'gallery',
    '/gallery/update' => 'gallery',
    '/gallery/delete' => 'gallery',
    '/gallery/insert' => 'gallery',
    '/admin' => 'MainAdmin',
    '/admin/' => 'MainAdmin',
    '/admin/update' => 'MainAdmin',
    '/admin/delete' => 'MainAdmin',
    '/admin/insert' => 'MainAdmin',
    '/admin/articlesAdmin' => 'ArticlesAdmin',
    '/admin/articlesAdmin/' => 'ArticlesAdmin',
    '/admin/articlesAdmin/update' => 'articlesAdmin',
    '/admin/articlesAdmin/delete' => 'articlesAdmin',
    '/admin/articlesAdmin/insert' => 'articlesAdmin',
    '/admin/usersAdmin' => 'UsersAdmin',
    '/admin/usersAdmin/' => 'UsersAdmin',
    '/admin/usersAdmin/update' => 'UsersAdmin',
    '/admin/usersAdmin/delete' => 'UsersAdmin',
    '/admin/usersAdmin/insert' => 'UsersAdmin',
];